### ISSUE TITLE
Evaluate per-server lisa state.

### ISSUE THREAD

**Issue by FelixRilling** [FelixRilling/lisa-bot#9]
Evaluate using a lisa state for each server either in addition to or replacing the current global state.

**Comment by FelixRilling** [comment]
Additionally, evaluate ways to change modifiers (e.g. water loss) per  server

**Comment by IBP-BOTMASTER** [comment]
Hey there! It's IBP. I am setting up a github feed channel on my server and was wonder if you had a webhook url I could use to add it in. (this is an experiment. I just joined github and have no idea what I'm doing.)

**Comment by FelixRilling** [comment]
> Hey there! It's IBP. I am setting up a github feed channel on my server and was wondering if you had a webhook url I could use to add it in. (this is an experiment. I just joined github and have no idea what I'm doing.)
I sent you a DM.
